### ISSUE TITLE
Cannot enter Molcar

### ISSUE THREAD

**Issue by hiewliwen** [Huanying04/Molcar#2]
Minecraft: 1.16.6
Fabric: 0.11.7
Curseforge: 0.185.4.3
Mode: Survival

Generated a new world. 
Right-click on Molcar but unable to enter it. 

Sidenote: how to get lettuce?

**Comment by Huanying04** [comment]
Sorry for replying so late that I just saw the issue.

In the latest version, you need to tame the Molcar with Lettuce Leaves first, which can be found in the villager's chest (also Lettuce Seeds), to enter them.

I think that you have the problem because I forgot to update the information in the description on the CurseForge page. I'll update it later.
